ALTER TABLE wallet_holdings
    ALTER COLUMN oz TYPE INTEGER USING round(oz)::INTEGER,
    ALTER COLUMN oz SET DEFAULT 0;

ALTER TABLE wallet_holdings
    ALTER COLUMN g24 TYPE NUMERIC(12, 1),
    ALTER COLUMN g21 TYPE NUMERIC(12, 1),
    ALTER COLUMN g18 TYPE NUMERIC(12, 1),
    ALTER COLUMN pounds TYPE NUMERIC(12, 1);
